version: "3"

services:
  postgres:
    image: postgres:latest
    networks:
      - postgres
    volumes:
      - task-unity-db:/data/postgres
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - task-unity-pgadmin:/root/.pgadmin
    env_file:
      - .env

  backend:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres

volumes:
  task-unity-db:
  task-unity-pgadmin:

networks:
  postgres:
    driver: bridge

